# Generated by Django 5.0.3 on 2024-04-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prd_name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.EmailField(blank=True, max_length=254, null=True)),
                ('prd_pric', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
